import { ChangeDetectionStrategy, Component, OnDestroy, OnInit, computed, inject, signal } from '@angular/core';
import { IonApp, IonButton, IonContent, IonIcon, IonInput, IonSelect, IonSelectOption, IonSpinner, IonText } from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import { albumsOutline, arrowBackOutline, checkmarkCircle, enterOutline, logInOutline, logOutOutline, musicalNotes, peopleOutline, personOutline, refreshOutline } from 'ionicons/icons';
import { Unsubscribe } from 'firebase/firestore';
import { BingoCardDocument, ParticipantDocument, PlayedSongDocument, RoomDocument, RoomNotFoundError, RoomSessionService, RoundDocument, RoundSong, SessionRole } from './core/firebase/room-session.service';

interface SpotifyImage { url: string; }
interface SpotifyUserProfile { id: string; product?: string; }
interface SpotifyArtist { name: string; }
interface SpotifyTrack { id:string; name:string; type:string; is_local?:boolean; artists:SpotifyArtist[]; album:{images:SpotifyImage[]}; external_urls:{spotify:string}; }
interface SpotifyPlaylistItem { item:SpotifyTrack|null; is_local?:boolean; track?:SpotifyTrack|null; }
interface SpotifyPlaylistItemsResponse { items:SpotifyPlaylistItem[]; next:string|null; }
interface SpotifyPlaylist { id:string; name:string; images:SpotifyImage[]; owner:{id:string;display_name:string|null}; items?:{total:number}; tracks?:{total:number}; }
interface SpotifyPlaylistsResponse { items:SpotifyPlaylist[]; next:string|null; }
interface SpotifyTokenResponse { access_token:string; expires_in:number; refresh_token?:string; }
interface SpotifyPlaybackState { progress_ms:number; is_playing:boolean; item:SpotifyTrack|null; }
type AppMode='name'|'choice'|'host'|'join'|'participant';

@Component({selector:'app-root',standalone:true,imports:[IonApp,IonContent,IonButton,IonIcon,IonInput,IonSelect,IonSelectOption,IonSpinner,IonText],templateUrl:'./app.component.html',styleUrl:'./app.component.scss',changeDetection:ChangeDetectionStrategy.OnPush})
export class AppComponent implements OnInit,OnDestroy{
 private readonly rooms=inject(RoomSessionService); private readonly clientId='abd77186596e467eb105868ffaff2b57';
 private readonly scopes=['playlist-read-private','playlist-read-collaborative','user-read-private','user-read-playback-state','user-modify-playback-state'];
 private readonly verifierKey='spotify_code_verifier';private readonly stateKey='spotify_auth_state';private readonly tokenKey='spotify_access_token';private readonly tokenExpiryKey='spotify_token_expiry';private readonly refreshTokenKey='spotify_refresh_token';private readonly roomCodeKey='bingo_room_code';private readonly roleKey='bingo_session_role';private readonly nameKey='bingo_display_name';private readonly bingoSize=15;
 private refreshPromise:Promise<string>|null=null;private roomUnsubscribe?:Unsubscribe;private participantsUnsubscribe?:Unsubscribe;private roundUnsubscribe?:Unsubscribe;private songsUnsubscribe?:Unsubscribe;private playedUnsubscribe?:Unsubscribe;private cardUnsubscribe?:Unsubscribe;private observedRoundId:string|null=null;
 readonly mode=signal<AppMode>('name');readonly displayName=signal('');readonly isRoomLoading=signal(false);readonly joinCode=signal('');readonly isLoading=signal(false);readonly isGeneratingCard=signal(false);readonly isConnected=signal(false);readonly isGameStarted=signal(false);readonly portraitNoticeVisible=signal(true);readonly playlists=signal<SpotifyPlaylist[]>([]);readonly selectedPlaylistId=signal<string|null>(null);readonly selectedPlaylist=computed(()=>this.playlists().find(p=>p.id===this.selectedPlaylistId())??null);readonly roomCode=signal('');readonly room=signal<RoomDocument|null>(null);readonly participants=signal<ParticipantDocument[]>([]);readonly activeRound=signal<RoundDocument|null>(null);readonly activeRoundId=signal<string|null>(null);readonly roundSongs=signal<RoundSong[]>([]);readonly playedSongs=signal<PlayedSongDocument[]>([]);readonly selectedPlayedSongId=signal<string|null>(null);readonly spotifyPremium=signal(false);readonly playbackAvailable=signal(false);readonly playbackBusy=signal(false);readonly currentSpotifyTrackId=signal<string|null>(null);readonly card=signal<BingoCardDocument|null>(null);readonly bingoTracks=computed(()=>{const byId=new Map(this.roundSongs().map(s=>[s.spotifyId,s]));return(this.card()?.songIds??[]).map(id=>byId.get(id)).filter((s):s is RoundSong=>Boolean(s));});readonly markedTrackIds=signal<Set<string>>(new Set());readonly errorMessage=signal<string|null>(null);
 constructor(){addIcons({albumsOutline,arrowBackOutline,checkmarkCircle,enterOutline,logInOutline,logOutOutline,musicalNotes,peopleOutline,personOutline,refreshOutline});}
 async ngOnInit(){const stored=localStorage.getItem(this.nameKey)??await this.rooms.loadDisplayName().catch(()=>'');this.displayName.set(stored);this.mode.set(stored?'choice':'name');await this.restoreSession();const p=new URLSearchParams(location.search);const code=p.get('code');if(p.get('error')){this.errorMessage.set('Spotify canceló o rechazó la autorización.');this.clearCallbackParameters();return;}if(code){this.mode.set('host');await this.completeAuthorization(code,p.get('state'));return;}if(this.mode()==='host'&&(sessionStorage.getItem(this.tokenKey)||localStorage.getItem(this.refreshTokenKey))){try{await this.getValidAccessToken();this.isConnected.set(true);await this.loadPlaylists();}catch(e){this.disconnect(false);this.errorMessage.set(e instanceof Error?e.message:'No se pudo recuperar Spotify.');}}}
 ngOnDestroy(){this.stopRealtimeListeners();}
 updateDisplayName(v:string|null|undefined){this.displayName.set((v??'').slice(0,40));this.errorMessage.set(null);} async confirmName(){this.isRoomLoading.set(true);try{const n=await this.rooms.saveDisplayName(this.displayName());this.displayName.set(n);localStorage.setItem(this.nameKey,n);this.mode.set('choice');}catch(e){this.errorMessage.set(e instanceof Error?e.message:'No se pudo guardar el nombre.');}finally{this.isRoomLoading.set(false);}}
 async chooseHost(){this.isRoomLoading.set(true);try{this.enterSession('host',await this.rooms.createHostRoom(this.displayName()));}catch(e){this.errorMessage.set(e instanceof Error?e.message:'No se pudo crear la partida.');}finally{this.isRoomLoading.set(false);}} showJoin(){this.joinCode.set('');this.mode.set('join');} updateJoinCode(v:string|null|undefined){this.joinCode.set((v??'').replace(/\D/g,'').slice(0,6));}
 async joinSession(){this.isRoomLoading.set(true);try{this.enterSession('participant',await this.rooms.joinRoom(this.joinCode(),this.displayName()));}catch(e){this.errorMessage.set(e instanceof RoomNotFoundError?e.message:e instanceof Error?e.message:'No se pudo entrar.');}finally{this.isRoomLoading.set(false);}}
 async leaveSession(){try{await this.rooms.leaveRoom(this.roomCode());}finally{this.stopRealtimeListeners();this.clearPersistedSession();this.roomCode.set('');this.resetRoundState();this.mode.set('choice');}} async closeHostSession(){try{await this.rooms.closeHostRoom(this.roomCode());}finally{await this.leaveSession();}} backToChoice(){this.mode.set('choice');}
 async regenerateRoomCode(){this.isRoomLoading.set(true);try{await this.rooms.closeHostRoom(this.roomCode());this.stopRealtimeListeners();this.enterSession('host',await this.rooms.createHostRoom(this.displayName()));}catch(e){this.errorMessage.set(e instanceof Error?e.message:'No se pudo generar otro número.');}finally{this.isRoomLoading.set(false);}}
 async connectWithSpotify(){const verifier=this.random(64);const challenge=await this.challenge(verifier);const state=this.random(24);sessionStorage.setItem(this.verifierKey,verifier);sessionStorage.setItem(this.stateKey,state);const params=new URLSearchParams({client_id:this.clientId,response_type:'code',redirect_uri:this.redirectUri(),scope:this.scopes.join(' '),code_challenge_method:'S256',code_challenge:challenge,state,show_dialog:'true'});location.assign(`https://accounts.spotify.com/authorize?${params}`);}
 selectPlaylist(id:string|null){this.selectedPlaylistId.set(id);} async startBingo(){const p=this.selectedPlaylist();if(!p)return;this.isGeneratingCard.set(true);try{const tracks=await this.loadPlaylistTracks(p.id);const songs=tracks.map((t,position)=>({spotifyId:t.id,name:t.name,artist:t.artists[0]?.name??'Artista desconocido',imageUrl:t.album.images[0]?.url??'',spotifyUrl:t.external_urls.spotify,position}));await this.rooms.startRound(this.roomCode(),p.id,p.name,songs);if(this.spotifyPremium())await this.startSpotifyPlaylist(p.id).catch(()=>this.playbackAvailable.set(false));}catch(e){this.errorMessage.set(e instanceof Error?e.message:'No se pudo iniciar.');}finally{this.isGeneratingCard.set(false);}}
 async endGame(){const id=this.activeRoundId();if(id)await this.rooms.finishRound(this.roomCode(),id).catch(e=>this.errorMessage.set(e.message));}
 async toggleTrack(id:string){const r=this.activeRoundId();if(!r||!this.card())return;const next=new Set(this.markedTrackIds());next.has(id)?next.delete(id):next.add(id);this.markedTrackIds.set(next);await this.rooms.updateMarkedSongs(this.roomCode(),r,[...next]).catch(()=>this.errorMessage.set('No se pudo guardar la casilla.'));}
 isTrackMarked(id:string){return this.markedTrackIds().has(id);} dismissPortraitNotice(){this.portraitNoticeVisible.set(false);} updatePlayedSongSelection(id:string|null){this.selectedPlayedSongId.set(id);}
 async markSelectedSong(){const id=this.selectedPlayedSongId();const roundId=this.activeRoundId();const song=this.roundSongs().find(s=>s.spotifyId===id);if(!id||!roundId||!song)return;await this.rooms.markSongPlayed(this.roomCode(),roundId,song,'manual');this.selectedPlayedSongId.set(null);}
 async togglePlayback(){await this.playbackCommand(async state=>{await this.spotifyFetch('https://api.spotify.com/v1/me/player/'+(state?.is_playing?'pause':'play'),{method:'PUT'});});}
 async nextTrack(){await this.playbackCommand(async()=>{await this.spotifyFetch('https://api.spotify.com/v1/me/player/next',{method:'POST'});});}
 async previousTrack(){await this.playbackCommand(async()=>{await this.spotifyFetch('https://api.spotify.com/v1/me/player/previous',{method:'POST'});});}
 async seekBy(delta:number){await this.playbackCommand(async state=>{const pos=Math.max(0,(state?.progress_ms??0)+delta);await this.spotifyFetch(`https://api.spotify.com/v1/me/player/seek?position_ms=${pos}`,{method:'PUT'});});}
 async markCurrentSpotifySong(){const roundId=this.activeRoundId();const state=await this.getPlaybackState();const song=this.roundSongs().find(s=>s.spotifyId===state?.item?.id);if(roundId&&song)await this.rooms.markSongPlayed(this.roomCode(),roundId,song,'spotify');}
 disconnect(clear=true){for(const k of [this.tokenKey,this.tokenExpiryKey,this.verifierKey,this.stateKey])sessionStorage.removeItem(k);localStorage.removeItem(this.refreshTokenKey);this.playlists.set([]);this.spotifyPremium.set(false);this.playbackAvailable.set(false);if(clear)this.errorMessage.set(null);this.isConnected.set(false);}
 private enterSession(role:SessionRole,code:string){localStorage.setItem(this.roleKey,role);localStorage.setItem(this.roomCodeKey,code);this.roomCode.set(code);this.mode.set(role==='host'?'host':'participant');this.startRealtimeListeners(code);}
 private startRealtimeListeners(code:string){this.stopRealtimeListeners();this.roomUnsubscribe=this.rooms.watchRoom(code,r=>{this.room.set(r);if(!r||r.status!=='open'){this.errorMessage.set('La sala se ha cerrado o ha caducado.');return;}if(r.currentRoundId!==this.observedRoundId)this.observeRound(code,r.currentRoundId);});if(this.mode()==='host')this.participantsUnsubscribe=this.rooms.watchParticipants(code,p=>this.participants.set(p));}
 private observeRound(code:string,id:string|null){this.stopRoundListeners();this.observedRoundId=id;this.activeRoundId.set(id);this.resetRoundState(false);if(!id)return;this.roundUnsubscribe=this.rooms.watchRound(code,id,r=>{this.activeRound.set(r);this.isGameStarted.set(r?.status==='active');});this.songsUnsubscribe=this.rooms.watchSongs(code,id,async songs=>{this.roundSongs.set(songs);if(songs.length>=15&&!this.card())await this.rooms.ensureCard(code,id,songs).catch(e=>this.errorMessage.set(e.message));});this.playedUnsubscribe=this.rooms.watchPlayedSongs(code,id,s=>this.playedSongs.set(s));this.cardUnsubscribe=this.rooms.watchCard(code,id,c=>{this.card.set(c);this.markedTrackIds.set(new Set(c?.markedSongIds??[]));});}
 private stopRealtimeListeners(){this.roomUnsubscribe?.();this.participantsUnsubscribe?.();this.stopRoundListeners();} private stopRoundListeners(){this.roundUnsubscribe?.();this.songsUnsubscribe?.();this.playedUnsubscribe?.();this.cardUnsubscribe?.();this.roundUnsubscribe=this.songsUnsubscribe=this.playedUnsubscribe=this.cardUnsubscribe=undefined;this.observedRoundId=null;}
 private resetRoundState(clear=true){if(clear)this.activeRoundId.set(null);this.activeRound.set(null);this.roundSongs.set([]);this.playedSongs.set([]);this.card.set(null);this.markedTrackIds.set(new Set());this.isGameStarted.set(false);}
 private async restoreSession(){const role=localStorage.getItem(this.roleKey) as SessionRole|null;const code=localStorage.getItem(this.roomCodeKey)??'';if((role==='host'||role==='participant')&&await this.rooms.resumeRoom(code,role))this.enterSession(role,code);} private clearPersistedSession(){localStorage.removeItem(this.roleKey);localStorage.removeItem(this.roomCodeKey);}
 private async loadPlaylistTracks(id:string){const out:SpotifyTrack[]=[];let next:string|null=`https://api.spotify.com/v1/playlists/${encodeURIComponent(id)}/items?limit=50&additional_types=track`;while(next){const r=await this.spotifyFetch(next);if(!r.ok)throw new Error('No se pudieron cargar las canciones.');const p=await r.json() as SpotifyPlaylistItemsResponse;for(const i of p.items){const t=i.item??i.track;if(t&&t.type==='track'&&!t.is_local&&t.id&&t.album.images.length)out.push(t);}next=p.next;}const unique=[...new Map(out.map(t=>[t.id,t])).values()];if(unique.length<15)throw new Error(`Esta playlist solo tiene ${unique.length} canciones válidas.`);return unique;}
 private async loadPlaylists(){this.isLoading.set(true);try{const profileResponse=await this.spotifyFetch('https://api.spotify.com/v1/me');if(!profileResponse.ok)throw new Error('No se pudo cargar tu perfil.');const profile=await profileResponse.json() as SpotifyUserProfile;this.spotifyPremium.set(profile.product==='premium');this.playbackAvailable.set(profile.product==='premium');const out:SpotifyPlaylist[]=[];let next:string|null='https://api.spotify.com/v1/me/playlists?limit=50';while(next){const r=await this.spotifyFetch(next);const p=await r.json() as SpotifyPlaylistsResponse;out.push(...p.items.filter(x=>x.owner.id===profile.id));next=p.next;}this.playlists.set(out);if(out.length===1)this.selectedPlaylistId.set(out[0].id);}finally{this.isLoading.set(false);}}
 private async startSpotifyPlaylist(id:string){await this.spotifyFetch('https://api.spotify.com/v1/me/player/shuffle?state=true',{method:'PUT'});const r=await this.spotifyFetch('https://api.spotify.com/v1/me/player/play',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({context_uri:`spotify:playlist:${id}`})});if(!r.ok)throw new Error();this.playbackAvailable.set(true);}
 private async playbackCommand(fn:(s:SpotifyPlaybackState|null)=>Promise<void>){this.playbackBusy.set(true);try{await fn(await this.getPlaybackState());this.playbackAvailable.set(true);}catch{this.playbackAvailable.set(false);this.errorMessage.set('Abre Spotify en un dispositivo y reproduce la playlist manualmente.');}finally{this.playbackBusy.set(false);}}
 private async getPlaybackState(){const r=await this.spotifyFetch('https://api.spotify.com/v1/me/player');if(r.status===204)return null;if(!r.ok)throw new Error();const state=await r.json() as SpotifyPlaybackState;this.currentSpotifyTrackId.set(state.item?.id??null);return state;}
 private async completeAuthorization(code:string,state:string|null){this.isLoading.set(true);try{if(state!==sessionStorage.getItem(this.stateKey))throw new Error('La respuesta de Spotify no supera la validación.');const verifier=sessionStorage.getItem(this.verifierKey);if(!verifier)throw new Error('Falta el verificador PKCE.');const body=new URLSearchParams({client_id:this.clientId,grant_type:'authorization_code',code,redirect_uri:this.redirectUri(),code_verifier:verifier});const r=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw new Error('Spotify no pudo completar el acceso.');this.storeToken(await r.json() as SpotifyTokenResponse);this.clearCallbackParameters();this.isConnected.set(true);await this.loadPlaylists();}catch(e){this.errorMessage.set(e instanceof Error?e.message:'No se pudo conectar.');}finally{this.isLoading.set(false);}}
 private async spotifyFetch(input:RequestInfo|URL,init:RequestInit={}){let token=await this.getValidAccessToken();let r=await fetch(input,this.authorized(init,token));if(r.status===401){token=await this.refreshAccessToken();r=await fetch(input,this.authorized(init,token));}return r;} private authorized(init:RequestInit,token:string){const h=new Headers(init.headers);h.set('Authorization',`Bearer ${token}`);return{...init,headers:h};}
 private async getValidAccessToken(){const t=sessionStorage.getItem(this.tokenKey);const e=Number(sessionStorage.getItem(this.tokenExpiryKey));return t&&Date.now()<e?t:this.refreshAccessToken();} private async refreshAccessToken(){if(this.refreshPromise)return this.refreshPromise;this.refreshPromise=this.requestRefresh();try{return await this.refreshPromise;}finally{this.refreshPromise=null;}} private async requestRefresh(){const rt=localStorage.getItem(this.refreshTokenKey);if(!rt)throw new Error('La sesión de Spotify ha caducado.');const body=new URLSearchParams({client_id:this.clientId,grant_type:'refresh_token',refresh_token:rt});const r=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw new Error('Spotify no pudo renovar la sesión.');const token=await r.json() as SpotifyTokenResponse;this.storeToken(token);return token.access_token;} private storeToken(t:SpotifyTokenResponse){sessionStorage.setItem(this.tokenKey,t.access_token);sessionStorage.setItem(this.tokenExpiryKey,String(Date.now()+t.expires_in*1000-60000));if(t.refresh_token)localStorage.setItem(this.refreshTokenKey,t.refresh_token);}
 private redirectUri(){return location.hostname==='localhost'||location.hostname==='127.0.0.1'?`http://127.0.0.1:${location.port||'8100'}/`:'https://zwymobile.com/bingo_musical/';} private clearCallbackParameters(){history.replaceState({},document.title,this.redirectUri());} private random(n:number){const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~';const values=crypto.getRandomValues(new Uint8Array(n));return Array.from(values,v=>chars[v%chars.length]).join('');} private async challenge(v:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return btoa(String.fromCharCode(...new Uint8Array(d))).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');}
}
